# Generated by Django 4.1 on 2022-08-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0002_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='img',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='socialApp/image/postImage'),
        ),
    ]
